services:
  graphDB:
    image: arangodb:latest
    container_name: hangar
    environment:
      ARANGO_ROOT_PASSWORD: arango
    ports:
      - 8529:8529
    volumes:
      - ./data:/var/lib/arangodb3
      - ./dumps:/dumps
